[package]
name = "Advent_of_Rust"
version = "0.1.0"
authors = ["JerryDot <dansinh64@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
