name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --manifest-path advent_of_rust/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path advent_of_rust/Cargo.toml
    - name: Clippy
      run: cargo clippy --manifest-path advent_of_rust/Cargo.toml -- -D warnings
    - name: Format
      run: cargo fmt --all --manifest-path advent_of_rust/Cargo.toml -- --check
